FROM node:18.13.0-alpine as builder
COPY . /app
WORKDIR /app
RUN npm install
#RUN npm run lint
#RUN npm run test
RUN npm run build

FROM nginx:1.17.10-alpine
# Base image
#FROM nginx:latest
# Set the working directory
#WORKDIR /usr/share/nginx/html
#EXPOSE 80

COPY --from=builder /app/dist/watson /usr/share/nginx/html
# Remove default Nginx files
RUN rm -rf ./*

# Copy the built AngularJS application into the container
#COPY dist/ .

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
